### ISSUE TITLE
Page Error: Cannot read property '0' of null

### ISSUE THREAD

**Issue by benaltair** [bahaistudies/conference#141]
http://localhost:3000/watch/honouring-children-truth-reconciliation-justice
```
TypeError: Cannot read property '0' of null
    at [slug].svelte:69:33
    at Object.$$render (D:\Github\conference\node_modules\svelte\internal\index.js:1380:22)
    at Object.default (root.svelte:38:46)
    at eval (D:\Github\conference\src\routes\__layout.svelte:38:36)
    at Object.$$render (D:\Github\conference\node_modules\svelte\internal\index.js:1380:22)
    at root.svelte:36:44
    at $$render (D:\Github\conference\node_modules\svelte\internal\index.js:1380:22)
    at Object.render (D:\Github\conference\node_modules\svelte\internal\index.js:1388:26)
    at render_response (file:///D:/Github/conference/node_modules/@sveltejs/kit/dist/ssr.js:377:28)
    at runMicrotasks (<anonymous>)
```
![image](https://user-images.githubusercontent.com/17771229/124034106-a8d57e00-d9af-11eb-972c-6559dd0a7448.png)

**Comment by benaltair** [comment]
Looks like one without a bg image - needs `if` wrapper.
```svelte
		{#if datetime}
			<section id="cta">
				<CTA --bg-photo="url('{photo[0].thumbnails.large.url}'" {datetime}>
					<p>
						Join a conversation about this presentation in&hellip;
						<Countdown {datetime} />
					</p>
				</CTA>
			</section>
		{/if}
```
