### ISSUE TITLE
On first load of dev server, error appears

### ISSUE THREAD

**Issue by benaltair** [bahaistudies/conference#144]
![image](https://user-images.githubusercontent.com/17771229/124506260-1e5e9700-dd80-11eb-9fd7-da668c1c54da.png)
```
TypeError: Line must be greater than or equal to 1, got -1
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/home/ben/Dev/conference/node_modules/vite/dist/node/chunks/dep-bc228bbb.js:67579:13)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/home/ben/Dev/conference/node_modules/vite/dist/node/chunks/dep-bc228bbb.js:67648:22)
    at /home/ben/Dev/conference/node_modules/vite/dist/node/chunks/dep-bc228bbb.js:68594:34
    at String.replace (<anonymous>)
    at /home/ben/Dev/conference/node_modules/vite/dist/node/chunks/dep-bc228bbb.js:68584:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/home/ben/Dev/conference/node_modules/vite/dist/node/chunks/dep-bc228bbb.js:68583:10)
    at Object.ssrFixStacktrace (/home/ben/Dev/conference/node_modules/vite/dist/node/chunks/dep-bc228bbb.js:68907:27)
    at Object.handle_error (file:///home/ben/Dev/conference/node_modules/@sveltejs/kit/dist/chunks/index.js:3359:19)
    at respond$1 (file:///home/ben/Dev/conference/node_modules/@sveltejs/kit/dist/ssr.js:988:11)
```

Then getting this error after - not sure if related at this stage, but doesn't seem so:
```
TypeError: Cannot read property 'default' of null
    at eval (/home/ben/Dev/conference/src/routes/index.svelte:42:66)
    at Object.$$render (/home/ben/Dev/conference/node_modules/svelte/internal/index.js:1380:22)
    at Object.default (root.svelte:38:46)
    at eval (/home/ben/Dev/conference/src/routes/__layout.svelte:38:36)
    at Object.$$render (/home/ben/Dev/conference/node_modules/svelte/internal/index.js:1380:22)
    at root.svelte:36:44
    at $$render (/home/ben/Dev/conference/node_modules/svelte/internal/index.js:1380:22)
    at Object.render (/home/ben/Dev/conference/node_modules/svelte/internal/index.js:1388:26)
    at render_response (file:///home/ben/Dev/conference/node_modules/@sveltejs/kit/dist/ssr.js:377:28)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

The second error seems to be talking about the `searchQuery` store, but not sure.

**Comment by benaltair** [comment]
So far doesn't seem to happen in prod, but should keep an eye out for it. If this doesn't happen in prod in the next week or so of testing, we can close this issue.
