### ISSUE TITLE
DayJS is tripping vite SSR

### ISSUE THREAD

**Issue by benaltair** [bahaistudies/conference#28]
Getting errors in `EventCard.svelte` on line 6 when mentioning the library.

**Comment by benaltair** [comment]
On the `event-page` branch, getting the same issue. 

The current `EventCard.svelte` `<script>` looks like this:
```html
<script lang="ts">
	import dayjs from 'dayjs';
	export let title: string = 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem';
	export let datetime = '2015-03-25T12:00:00-07:00'; // Providing an example date during dev
	export let date: string = dayjs(datetime).format('d MMMM, h:mma');

	export let duration: string = '20';
	export let category: string = 'Presentation';
	export let slug: string = 'lorem-ipsum';
	let link: string = '/events/' + slug;
	export let size: 'small' | 'medium' | 'large' = 'small';
	export let width: number = 600;
	export let height: number = 400;
	var urlTitle = encodeURIComponent(title);
	export let photo: string = 'https://picsum.photos/seed/' + urlTitle + '/' + width + '/' + height;
</script>
```


Here's the error:
```text
TypeError: __vite_ssr_import_1__.default is not a function
    at EventCard.svelte:5:33
    at Object.$$render (D:\Github\conference\node_modules\svelte\internal\index.js:1369:22)
    at eval (D:\Github\conference\src\routes\index.svelte:20:144)
    at Object.$$render (D:\Github\conference\node_modules\svelte\internal\index.js:1369:22)
    at Object.default (root.svelte:46:46)
    at eval (D:\Github\conference\src\routes\$layout.svelte:26:66)
    at Object.$$render (D:\Github\conference\node_modules\svelte\internal\index.js:1369:22)
    at root.svelte:42:13
    at $$render (D:\Github\conference\node_modules\svelte\internal\index.js:1369:22)
    at Object.render (D:\Github\conference\node_modules\svelte\internal\index.js:1377:26)
```

![image](https://user-images.githubusercontent.com/17771229/113051905-5fc92000-915b-11eb-85a9-e32efe9286bf.png)

**Comment by benaltair** [comment]
Removing DayJS stops this problem immediately. On `master` this has temporarily been dealt with during dev by replacing the date with a static placeholder:
```js
import dayjs from "dayjs";
export let title: string = 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem';
export let datetime = '2015-03-25T12:00:00-07:00'; // Providing an example date during dev
// export let date: string = dayjs(datetime).format('d MMMM, h:mma');
export let date: string = "Tuesday, 28 July"
```

Related to #32, but it's a weird issue as other NPM packages are imported this way it seems in Svelte.
