### ISSUE TITLE
Fix Firebase intitialization

### ISSUE THREAD

**Issue by AverageTrout** [bahaistudies/conference#70]
Looks like Firebase isn't initialized too well, not sure if its a problem in `index.svelte` or `firebase.js`
![image](https://user-images.githubusercontent.com/36682923/114287245-57ee6300-9a1a-11eb-88ae-b5bea5281fb7.png)
Related to #25

**Comment by benaltair** [comment]
Made some adjustments. Throwing this error currently:
```
FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
    at app (D:\Github\conference\node_modules\@firebase\app\dist\index.node.cjs.js:356:33)
    at Object.serviceNamespace [as auth] (D:\Github\conference\node_modules\@firebase\app\dist\index.node.cjs.js:406:51)
    at /src/lib/firebase.js:20:30
    at instantiateModule (D:\Github\conference\node_modules\vite\dist\node\chunks\dep-66eb515d.js:69030:166)
```

**Comment by benaltair** [comment]
Firebase is now initializing correctly client-side. We next need to handle the reactivity
